# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

pool:
  vmImage: '$(VMIMAGE)'

steps:
- script: |
    git clone -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" "https://constructors.visualstudio.com/_git/MicrosoftSamples" "$BUILD_SOURCESDIRECTORY/ci"
  displayName: 'Clone DevOps repo'

- checkout: none
  path: dotnet-samples
  displayName: 'Check out dotnet/samples repo'

- script: |
    echo Init dotnet
    dotnet help &> /dev/null
    echo Find projects in dotnet-samples folder 
    dotnet run -- $BUILD_SOURCESDIRECTORY/dotnet-samples/core
  displayName: 'Run find-projects tool'
  workingDirectory: $BUILD_SOURCESDIRECTORY/ci/find-projects