# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
- master

pr: none

jobs:
- job:
  displayName: 'Run Linux Tests'

  pool:
    vmImage: '$(VMIMAGE)'

  steps:

  - script: |
      echo Init dotnet
      dotnet help &> /dev/null
      echo Find projects in dotnet-samples folder 
    displayName: 'Test dotnet'