# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

pool:
  vmImage: '$(VMIMAGE)'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    dotnet --info
  displayName: 'Check .NET Core version'

- script: |
    git clone -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" "https://constructors.visualstudio.com/_git/MicrosoftSamples" "$BUILD_SOURCESDIRECTORY/ci"
  displayName: 'Clone DevOps repo'
