# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr: 
- master

pool:
  vmImage: '$(VMIMAGE)'

steps:

- checkout: self
  path: dotnet-samples
  persistCredentials: true
  displayName: 'Check out dotnet/samples repo'
