# This is a basic workflow to help you get started with Actions
name: Snippets 5000

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    paths:
      - "**.cs"
      - "**.vb"
      - "**.fs"
      - "**.cpp"
      - "**.h"
      - "**.xaml"
      - "**.razor"
      - "**.cshtml"
      - "**.vbhtml"
      - "**.*proj"
      - "**global.json"
    branches: [ master ]

env:
  DOTNET_VERSION: '3.1.300'           # set this to the dot net version to use

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    # Install locate projs global tool
    - name: Install LocateProjects tool
      run: |
        dotnet tool install --global --add-source ./.github/workflows/dependencies/ DotnetDocsTools.LocateProjects
    
    # Run locate projs tool
    - name: Locate projects for PR
      env:
        GitHubKey: ${{ secrets.GITHUB_TOKEN }}
        LocateExts: ".cs;.vb;.fs;.cpp;.h;.xaml;.razor;.cshtml;.vbhtml;.csproj;.fsproj;.vbproj;.sln"
      run: |
        ./.github/workflows/dependencies/Get-MSBuildResults.ps1 "${{ github.workspace }}" -PullRequest ${{ github.event.number }} -RepoOwner ${{ github.repository_owner }} -RepoName ${{ github.event.repository.name }}
        
    # Update build output json file
    - name: Upload build results
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: ./output.json

    # Return status based on json file
    - name: Report status
      run: |
        ./.github/workflows/dependencies/Out-GithubActionStatus.ps1
      
      
      
